var radical_explanations = {
"亻":"radical for human, derived from the kanji",
"隹":"bird/old bird radical (turkey?)",
"儿":"legs radical",
"禾":"Two-branch tree radical",
"厶":"private/myself radical",
"彳":"stop, lingering, loitering man radical",
"欠":"lack, gap, fail, yawning radical",
"冖":"crown, roof radical",
"卜":"fortune-telling radical",
"亠":"top hat, kettle lid radical",
"斤":"axe radical",
"乙":"fish hook, eel radical",
"冫":"water/ice radical",
"夂":"late/delayed and walking legs radical",
"幺":"short thread/cocoon radical",
"聿":"brush radical",
"豕":"pig radical",
"⻌":"walk/road radical",
"匕":"spoon radical",
"疒":"sickness radical",
"巾":"towel, hanging scroll radical",
"尸":"corpse/flag radical",
"广":"house on cliff radical",
"氵":"splash of water"
};
